sudo: false
language: c
env: VERBOSE=1

addons:
  apt:
    packages:
      - build-essential
      - pkg-config
      - libncursesw5-dev
      - libslang2-dev
      - libx11-dev
      - libimlib2-dev
      - freeglut3-dev
      # FIXME: disable this for now, as it just outputs garbage
      #- texlive-fonts-recommended
      #- doxygen-latex
      - ruby-dev
      - ruby-minitest

# Travis does shallow clones, but we use the Git history
# for check-copyright. Disable shallow clones; our whole
# history is about 5 MiB anyway.
git:
  depth: 9999999

before_install:
  - .travis/before_install.sh
  - ./bootstrap

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

